version: 0.2

phases:
	build:
		commands:
			- echo Entra a la fase de construccion...
			- mvn clean package
	post_build
		commands:
			- echo Construccion Completada...
artifacts:
	files:
		- target/demo.jar
	discard-paths: yes