version: 0.2

phases:
  build:
    commands:
      - echo Construyendo el paquete
      - mvn clean package
  post_build:
    commands:
      - echo Construccion completada
artifacts:
  files:
    - target/demo-0.0.1-SNAPSHOT.jar
  discard-paths: yes