version: 0.2

phases:
  build:
    commands:
      - echo Contruyendo el paquete
      - mvn clean package
  post_build:
    commands:
      - echo Contruccion completada
artifacts:
  files:
    - target/demo.jar
  discard-paths: yes